lcpp-org/crane

include/actions/ChemicalReactionsBase.h, src/actions/AddScalarReactions.C, src/actions/ChemicalReactionsBase.C
This PR adds functionality to the EEDF rate coefficient identifier. Instead of forcing the user to create files that are named based on the reaction, they can now specify which file to look for by enclosing the file name in parentheses, e.g. 
e + Ar -> e + e + Ar+  : EEDF (file_name.txt)
=> EEDF reaction file names can now be specified

src/actions/AddScalarReactionsOld.C, src/actions/AddZapdosReactions.C, src/actions/ChemicalReactions.C, src/scalarkernels/Reactant2BodyScalar.C
These variables were all local variables that were unused. In the `_energy_change` case you actually had the dangerous behavior that you were modifying a local when you probably thought you were operating on the class member variable.
=> Add fixups for -Werror with gcc

src/actions/AddReactions.C
We just updated to llvm-8, and the new compiler stack is now catching this unused variable.
=> Delete unused variable

include/kernels/ProductFirstOrder.h, include/kernels/ProductFirstOrderLog.h, include/kernels/ProductSecondOrder.h, include/kernels/ProductSecondOrderLog.h, include/kernels/ProductThirdOrder.h, include/kernels/ProductThirdOrderLog.h, include/kernels/ReactantFirstOrderLog.h, include/kernels/ReactantSecondOrder.h, include/kernels/ReactantSecondOrderLog.h, include/kernels/ReactantThirdOrder.h, include/kernels/ReactantThirdOrderLog.h, src/actions/AddZapdosReactions.C, src/base/CraneApp.C, src/kernels/ProductFirstOrder.C, src/kernels/ProductFirstOrderLog.C, src/kernels/ProductSecondOrder.C, src/kernels/ProductSecondOrderLog.C, src/kernels/ProductThirdOrder.C, src/kernels/ProductThirdOrderLog.C, src/kernels/ReactantFirstOrderLog.C, src/kernels/ReactantSecondOrder.C, src/kernels/ReactantSecondOrderLog.C, src/kernels/ReactantThirdOrder.C, src/kernels/ReactantThirdOrderLog.C
This PR has a few substantial updates. The largest one is a new Action syntax that allows multiple action blocks to be added like so: 
[Reactions]
[./block0]
species = ...
reactions = ...
block = 0
[../]
[./block1]
...
block = 1
[../]
[]
**Note: right now this is exclusively for Zapdos actions (e.g. it uses the AddZapdosReaction class). I'd like to make this syntax applicable to the other classes, but Zapdos is the most important use case at the moment.**
Other important changes: 
1. **References to the material property _n_gas were removed.** All reactants **must** be either nonlinear or auxiliary variables now. It didn't make sense to refer to "n_gas" for reactions in water, for example.
2. **Kernel off-diagonal Jacobian bug fixes.** Found a few small errors in some of the Kernels. They …
=> Adding Multiple Action Blocks

include/kernels/ElectronEnergyTermElasticTownsend.h, include/kernels/ElectronEnergyTermTownsend.h, include/kernels/ElectronImpactReactionProduct.h, include/kernels/ElectronImpactReactionReactant.h, include/kernels/ElectronReactantSecondOrderLog.h, include/materials/EEDFRateConstantTownsend.h, src/actions/AddZapdosReactions.C, src/kernels/ElectronEnergyTermElasticTownsend.C, src/kernels/ElectronEnergyTermTownsend.C, src/kernels/ElectronImpactReactionProduct.C, src/kernels/ElectronImpactReactionReactant.C, src/kernels/ElectronProductSecondOrderLog.C, src/kernels/ElectronReactantSecondOrderLog.C, src/materials/EEDFRateConstantTownsend.C
This PR adds kernels for reactions using the Townsend formulation rather than standard rate coefficients.
=> Adding kernels for electron-impact reactions under the Townsend formulation

src/actions/AddReactions.C, src/actions/AddZapdosReactions.C
This PR just addresses a couple bugs in the action system. 
1. Adds auxiliary variable support to AddReactions (for spatial problems without Zapdos)
2. Fixes bug in which reactants were not recognized when using normal (non-Townsend) reaction formulation in Zapdos
=> Fixing block identification bug in action

include/actions/ChemicalReactionsBase.h, include/auxkernels/ProcRateForRateCoeffThreeBody_Crane.h, include/auxkernels/ProcRateForRateCoeff_Crane.h, include/auxkernels/ProcRateForRateCoeff_OneBody_Crane.h, include/auxkernels/ProcRateForRateCoeff_Townsend_Crane.h, include/auxkernels/ProductionFirstOrder.h, include/auxkernels/ProductionSecondOrder.h, include/auxkernels/ProductionThirdOrder.h, problems/e4.i, problems/e5.i, problems/e5_plot.py, problems/e5_track.i, problems/example1.i, problems/example1_spatial.i, src/actions/AddScalarReactions.C, src/actions/AddZapdosReactions.C, src/actions/ChemicalReactionsBase.C, src/auxkernels/ProcRateForRateCoeffThreeBody_Crane.C, src/auxkernels/ProcRateForRateCoeff_Crane.C, src/auxkernels/ProcRateForRateCoeff_OneBody_Crane.C, src/auxkernels/ProcRateForRateCoeff_Townsend_Crane.C, src/auxkernels/ProductionFirstOrder.C, src/auxkernels/ProductionSecondOrder.C, src/auxkernels/ProductionThirdOrder.C, src/kernels/ElectronImpactReactionProduct.C, src/kernels/ElectronProductSecondOrderLog.C
Added auxiliary kernels to calculate the production rate of each species at the end of each timestep, to allow outputting of the production rate from each reaction as a function of time at each point in space. Rates are tracked by default, and can be turned off by including "track_rates = false" in the chemical_reactions block of the input file.
=> Added ability to track production rates of each species

include/actions/ChemicalReactionsBase.h, src/actions/AddScalarReactions.C, src/actions/ChemicalReactionsBase.C
This PR adds support for a lumped species variable, intended to be used for situations in which many identical reactions may occur with any of the neutral species in the system. For example:
O- + N+ + [any neutral species] -> O + N + [any neutral species]
Rather than adding multiple identical reactions with only one species changed, a lumped variable may be defined in the action's parameters: 
lumped_species = true
lumped = 'N2 O2 N ...'
lumped_name = 'NEUTRAL'
reactions = 'O- + N+ + NEUTRAL -> O + N + NEUTRAL : 1e-20'
If "NEUTRAL" accounts for 10 species, the ChemicalReactions action will automatically split this reaction into 10 with the appropriate reactants and products. 
Note that the same system may also be addressed with an auxiliary variable without adding more reactions, e.g. add …
=> Lumped species for similar reactions

include/actions/ChemicalReactionsBase.h, include/auxkernels/VariableSumLog.h, include/scalarkernels/Product1BodyScalar.h, include/scalarkernels/Product1BodyScalarLog.h, include/scalarkernels/Product2BodyScalar.h, include/scalarkernels/Product2BodyScalarLog.h, include/scalarkernels/Product3BodyScalar.h, include/scalarkernels/Product3BodyScalarLog.h, include/scalarkernels/Reactant1BodyScalar.h, include/scalarkernels/Reactant1BodyScalarLog.h, include/scalarkernels/Reactant2BodyScalar.h, include/scalarkernels/Reactant2BodyScalarLog.h, include/scalarkernels/Reactant3BodyScalar.h, include/scalarkernels/Reactant3BodyScalarLog.h, src/actions/AddScalarReactions.C, src/actions/ChemicalReactionsBase.C, src/auxkernels/VariableSumLog.C, src/scalarkernels/Product1BodyScalar.C, src/scalarkernels/Product1BodyScalarLog.C, src/scalarkernels/Product2BodyScalar.C, src/scalarkernels/Product2BodyScalarLog.C, src/scalarkernels/Product3BodyScalar.C, src/scalarkernels/Product3BodyScalarLog.C, src/scalarkernels/Reactant1BodyScalar.C, src/scalarkernels/Reactant1BodyScalarLog.C, src/scalarkernels/Reactant2BodyScalar.C, src/scalarkernels/Reactant2BodyScalarLog.C, src/scalarkernels/Reactant3BodyScalar.C, src/scalarkernels/Reactant3BodyScalarLog.C
Fixes a bug in the log scalar kernel jacobians. Also consolidates all exponential multiplications under a log formulation into a single exp(...) to save computational time since std::exp can be expensive. (e.g. exp(n1) * exp(n2) * exp(n3) is now exp(n1 + n2 + n3))
Adds AuxKernel for computing the sum of species in log form.
=> Fixing scalar log kernel bugs; general cleanup of files

include/actions/ChemicalReactionsBase.h, src/actions/AddScalarReactions.C, src/actions/ChemicalReactionsBase.C
A recent PR that allowed multiple blocks of reactions to exist caused tests to fail due to variable names being slightly different ("rate_constant0" became "_rate_constant0"). This PR fixes the issue.
=> Fixing variable name discrepancy, causing test failure

src/actions/ChemicalReactionsBase.C, src/kernels/EEDFElasticTownsendLog.C, src/kernels/EEDFEnergyTownsendLog.C, src/kernels/EEDFReactionTownsendLog.C, src/kernels/ReactionSecondOrderEnergyLog.C, src/kernels/ReactionSecondOrderLog.C, src/kernels/ReactionThirdOrderEnergyLog.C, src/kernels/ReactionThirdOrderLog.C
Changes include the following: 
1. Reduces number of std::exp() calls in reaction kernels: exp(var1) * exp(var2) becomes exp(var1 + var2). Has a small but noticeable effect on computational time - with a 10 reaction test, 10 timesteps took 64 seconds prior to this change and 60.6 seconds after. This becomes significant when a large number of reactions are considered.
2. Addresses unit conversion bug in Action. Constant and Function rate coefficients may have their units converted automatically from the input file with the "convert_to_moles" and "convert_to_meters"  options, but three body reactions were not converted to molar units properly. This PR fixes the bug.
=> Performance update

include/auxkernels/ParsedAuxScalar.h, include/auxkernels/ParsedScalarRateCoefficient.h, src/auxkernels/ParsedAuxScalar.C, src/auxkernels/ParsedScalarRateCoefficient.C
I renamed `ADFunction` to `SymFunction` to avoid confusion with upcoming AD'ified function objects. `FunctionParserUtils` is now a template that takes a bool parameter, choosing between a regular and a dual number version (forward mode AD).
This should probably get merged after https://github.com/idaholab/moose/pull/15331 is in
Closes #57
=> Update for API changes 

src/userobjects/BoltzmannSolverScalar.C
On my system there's a pragma that warns me if I don't catch the return
value of system calls, probably because they're pretty important.
Cataching the return values and then checking for errors to make sure I
don't get any unused variable warnings removes all warnings for me. Also
who doesn't want some C-looking code in their C++? :-)
=> Catch system call return values

include/materials/ADEEDFRateConstantTownsend.h, include/materials/ADZapdosEEDFRateConstant.h, src/kernels/ADEEDFElasticTownsendLog.C, src/kernels/ADEEDFEnergyTownsendLog.C, src/kernels/ADEEDFReactionTownsend.C, src/materials/ADEEDFRateConstantTownsend.C, src/materials/ADZapdosEEDFRateConstant.C
Converts linear interpolation to spline interpolation for automatic differentiation rate coefficients. 
Splines have better convergence properties and smooth derivatives. In addition, linear interpolations will throw a standard library error if the sample is out of range. Standard library errors are not caught by MOOSE and will terminate the program rather than simply cutting the timestep.
=> Converting linear interpolation to splines

include/actions/AddScalarReactions.h, include/auxkernels/ScalarLinearInterpolation.h, include/auxkernels/ScalarSplineInterpolation.h, src/actions/AddScalarReactions.C, src/auxkernels/ScalarLinearInterpolation.C, src/auxkernels/ScalarSplineInterpolation.C, tests/scalar_network/zdplaskin_ex1.i, tests/scalar_network/zdplaskin_ex2.i, tests/scalar_network/zdplaskin_ex3.i
Replaces the DataReadScalar AuxKernel with two classes: 
1. ScalarLinearInterpolation
2. ScalarSplineInterpolation
so the user may now select which type of interpolation they want. This also required modifying the action to point to the appropriate AuxKernel. An input parameter called "interpolation_type" was added to the action, with accepted inputs of "linear" and "spline". The default option is now set to 'linear'.  
All three tests needed to be modified as well since the "gold" output files were created using splines. (The solutions using linear interpolations vs splines were only different by a factor of 1e-4, but this was enough to throw a test failure.) 
Note that this PR only affects scalar problems. 1D-3D problems  still default to splines.
EDIT: spelling and grammar. That's what …
=> Linear interpolations

include/actions/AddReactions.h, include/auxkernels/ReactionRateFirstOrder.h, include/auxkernels/ReactionRateSecondOrder.h, include/auxkernels/ReactionRateThirdOrder.h, src/actions/AddReactions.C, src/actions/ChemicalReactionsBase.C, src/auxkernels/ReactionRateFirstOrder.C, src/auxkernels/ReactionRateSecondOrder.C, src/auxkernels/ReactionRateThirdOrder.C
This PR fixes a few deprecated kernel names for spatial reaction networks in the AddReactions class. (Note that this only affects reaction networks that are used with Crane itself, not Zapdos.) Also updates the AddReactions class to be more similar to the AddZapdosReactions version.
=> Replacing deprecated kernel names in AddReactions

include/actions/AddScalarReactions.h, src/actions/AddScalarReactions.C
Addresses a minor variable name error that caused test failure. Note that this had no effect on the results of any simulations; the names of the auxiliary variables storing the rate coefficient data were simply different between new output files and the older test output files. The numbers were correct, but the tests failed because they were trying to compare variables with different names.
Closes issue #63.
=> Fixing AuxScalarVariable naming bug

include/userobjects/BoltzmannSolverScalar.h
This is required for the passing of Zapdos after the merge of https://github.com/idaholab/moose/pull/17380
=> Make scalar variable values const-correct

src/actions/AddReactions.C
Fixes up some warnings experienced when updating the crane submodule in shannon-lab/zapdos#83.
Ping @keniley1 for review and merge.
=> Remove unused variables in AddReactions.C

include/kernels/ReactionSecondOrderLog.h, include/kernels/ReactionThirdOrderLog.h, include/materials/GenericRateConstant.h, src/kernels/ReactionSecondOrderLog.C, src/kernels/ReactionThirdOrderLog.C, src/materials/GenericRateConstant.C
Updates the following classes to AD templates and cleans extraneous code and comment cruft:
- ReactionSecondOrderLog
- ReactionThirdOrderLog
- GenericRateConstant
@keniley1 This change is in support of converting Zapdos to AD (specifically, to fixup the shooting method acceleration tests). Refs shannon-lab/zapdos#80
=> Add new templates in support of Zapdos AD conversion

include/kernels/TimeDerivativeLog.h, src/kernels/TimeDerivativeLog.C, src/materials/ADZapdosEEDFRateConstant.C
The recent removal of the positivity constraint in ADZapdosEEDFRateConstant in #71 caused a failure in the shooting method test in shannon-lab/zapdos#80. This PR restores that constraint. 
This PR also converts TimeDerivativeLog to AD (so that ADTimeDerivativeLog in Zapdos can just be removed). Tested as working against current CRANE tests on MacOS with Big Sur 11.2.1
=> Restore positivity constraint in ADZapdosEEDFRateConstant and Convert TimeDerivativeLog to AD

src/materials/InterpolatedCoefficientLinear.C
MOOSE/libMesh use C++17 now, so libmesh_make_unique is deprecated.
=> Use std::make_unique in InterpolatedCoefficientLinear

.gitmodules
=> Add moose submodule

_config.yml
Refs #87
@smpeyres I think this should fix the broken GitHub deployment runner.
=> Add _config.yml to exclude MOOSE submodule from Jekyll build

tests/scalar_network/zdplaskin_ex2.i
CRANE is failing CIVET testing with the following error:
```
scalar_network.zdplaskin_ex2: *** ERROR ***
scalar_network.zdplaskin_ex2: /data/civet2/build/crane/tests/scalar_network/zdplaskin_ex2.i:73: unused parameter 'ChemicalReactions/ScalarNetwork/reaction_coefficient_format'
```
This param was removed from AddScalarReactions some time ago, so this PR fixes that up in example 2
=> Remove unused parameter from zdplaskin example 2

src/actions/AddZapdosReactions.C
This fix is related to parsed function changes in MOOSE.
=> Fixup deprecated code in AddZapdosReactions

include/postprocessors/ElectricFieldCalculator.h, src/postprocessors/ElectricFieldCalculator.C
Zapdos is currently failing devel testing due to a change in MOOSE that adds const-ness to the postprocessor `getValue()` method: https://civet.inl.gov/event/138892/.
This PR adds const-ness to that in `ElectricFieldCalculator` and updates the MOOSE submodule.
Tagging @smpeyres and @dcurreli for review and merge. This is necessary to get shannon-lab/zapdos#203 passing.
=> Add const to getValue method in ElectricFieldCalculator

include/postprocessors/ElectricFieldCalculator.h
One more fixup here @smpeyres, as I missed this in the previous PR (only shows up in debug mode). Ready for review and merge. 
refs shannon-lab/zapdos#203
=> Make sure overload resolution occurs with the right getValue

src/actions/ChemicalReactions.C, src/actions/ChemicalReactionsBase.C
Refer to the issue [#24455](https://github.com/idaholab/moose/issues/24455), a fix is introduced to MOOSE to properly report error when no default value is provided for vector type input parameter. This new fix in MOOSE cause several tests failed in Crane which don't provide default value for vector parameter. 
This patch is made to fix the failed Crane tests due to the new changes in MOOSE
=> Add default value for vector type input parameters

docs/source/index.rst, docs/source/references.rst, docs/source/refs.bib
See Title. I linked ‘CRANE’ to the arXiv preprint instead of the github page (since most people get to the ReadTheDocs through the GitHub, and not the other way around) following the hpic2 ReadTheDocs, but let me know if you want this reversed.
=> [DOCS] Added References to ReadTheDocs; cited arXiv preprint in welcome page

include/utils/CraneUtils.h, src/actions/AddGeneralReactions.C, src/actions/AddScalarReactions.C, src/actions/AddZapdosReactions.C, src/actions/ChemicalReactions.C, src/actions/ChemicalReactionsBase.C, src/auxkernels/DataRead.C, src/auxkernels/ElectronMobility.C, src/auxkernels/ScalarLinearInterpolation.C, src/auxkernels/ScalarSplineInterpolation.C, src/materials/ADEEDFRateConstantTownsend.C, src/materials/ADZapdosEEDFRateConstant.C, src/materials/DiffusionRateTemp.C, src/materials/EEDFRateConstant.C, src/materials/EEDFRateConstantTownsend.C, src/materials/ElectricField.C, src/materials/HeatCapacityRatio.C, src/materials/InterpolatedCoefficientLinear.C, src/materials/InterpolatedCoefficientSpline.C, src/materials/SuperelasticReactionRate.C, src/materials/ZapdosEEDFRateConstant.C, src/scalarkernels/ParsedScalarReaction.C, src/userobjects/PolynomialCoefficients.C, src/userobjects/RateCoefficientProvider.C, src/userobjects/ValueProvider.C, src/utils/CraneUtils.C
refs idaholab/moose#26947
Requires https://github.com/idaholab/moose/pull/27143 and is in support of https://github.com/idaholab/moose/issues/26947
All `file_location` parameters are set to the `FileName` type, which eventually will be auto filled with the correct absolute path to the file base. For objects that have a default, the default is set to `.` (cwd of the input file). All `property_file` parameters are set to the `RelativeFileName` type, which means don't have their absolute paths resolved so you can do `<file_location>/<property_file>`.
=> Correct file path management

docs/source/build.rst
Previous implementation did not include explicit steps to activate conda and to navigate to crane directory before trying make.
=> Update build.rst – more specific clone & compile instructions
